### ISSUE TITLE
Running si-scrape.rb

### ISSUE THREAD

**Issue by nancyum** [mdlincoln/si-scrape#5]
Hi Matthew -

Was very happy to find this tool, but can't get it to run.

ruby: No such file or directory -- si-scrape.rb (LoadError)

Then again, I am new to ruby. Help!

Nancy

**Comment by mdlincoln** [comment]
You may find some help here: https://stackoverflow.com/questions/8721369/how-to-execute-a-ruby-script-in-terminal#8721391
